name: whsun-docs
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - expat=2.6.3=h6a678d5_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py312h06a4308_0
  - python=3.12.5=h5148396_1
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.44.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - babel==2.16.0
    - certifi==2024.8.30
    - charset-normalizer==3.3.2
    - click==8.1.7
    - colorama==0.4.6
    - ghp-import==2.1.0
    - idna==3.10
    - jinja2==3.1.4
    - markdown==3.7
    - markupsafe==2.1.5
    - mergedeep==1.3.4
    - mkdocs==1.6.1
    - mkdocs-get-deps==0.2.0
    - mkdocs-material==9.5.34
    - mkdocs-material-extensions==1.3.1
    - packaging==24.1
    - paginate==0.5.7
    - pathspec==0.12.1
    - platformdirs==4.3.3
    - pygments==2.18.0
    - pymdown-extensions==10.9
    - python-dateutil==2.9.0.post0
    - pyyaml==6.0.2
    - pyyaml-env-tag==0.1
    - regex==2024.9.11
    - requests==2.32.3
    - six==1.16.0
    - urllib3==2.2.3
    - watchdog==5.0.2
